#!/usr/bin/env python3
"""Generate the ZMK physical layout + matrix transform from the board geometry.

Keeps ZMK Studio's key map in exact agreement with the PCB (same ergogen source).

usage: gen_zmk_layout.py <geometry_left.json> <geometry_right.json> <out.dtsi>
"""
import json
import sys

UNIT = 18.0  # mm per ZMK layout unit (choc spacing)
COLS = ["C1", "C2", "C3", "C4", "C5", "C6"]


def ordered_keys(left, right):
    def by(side, row, col):
        for k in side["keys"]:
            if k["row"] == row and k["col"] == col:
                return k
        raise KeyError((row, col))

    def bay(side):
        b = side["ball"]
        return {"x": b["x"], "y": b["y"], "r": 0, "row": "R4", "col": "C1", "bay": True}

    order = []  # (key, matrix_row, matrix_col)
    for r, row in enumerate(["R1", "R2", "R3"]):
        for c in reversed(range(6)):
            order.append((by(left, row, COLS[c]), r, c))
        for c in range(6):
            order.append((by(right, row, COLS[c]), r, 6 + c))
    for c in (3, 2, 1):
        order.append((by(left, "R4", COLS[c]), 3, c))
    order.append((bay(left), 3, 0))
    order.append((bay(right), 3, 6))
    for c in (1, 2, 3):
        order.append((by(right, "R4", COLS[c]), 3, 6 + c))
    return order


def main(lpath, rpath, out):
    left, right = json.load(open(lpath)), json.load(open(rpath))
    order = ordered_keys(left, right)
    minx = min(k["x"] for k, _, _ in order) - UNIT / 2
    miny = min(k["y"] for k, _, _ in order) - UNIT / 2
    # close the (arbitrary) gap between the halves to 3u so the Studio view stays compact
    lmax = max(k["x"] for k, _, c in order if c < 6)
    rmin = min(k["x"] for k, _, c in order if c >= 6)
    squeeze = (rmin - lmax) - 4 * UNIT
    attrs, rc = [], []
    for k, row, col in order:
        cx = (k["x"] - (squeeze if col >= 6 else 0) - minx) / UNIT * 100
        cy = (k["y"] - miny) / UNIT * 100
        w, h = (150, 150) if k.get("bay") else (100, 94)
        r = int(round(-k["r"] * 100))
        attrs.append(f"<&key_physical_attrs {w:4d} {h:4d} {int(cx - w / 2):5d} {int(cy - h / 2):5d} "
                     f"{('(' + str(r) + ')') if r < 0 else r:>7} {int(cx):5d} {int(cy):5d}>")
        rc.append(f"RC({row},{col})")
    rows = [rc[0:12], rc[12:24], rc[24:36], rc[36:44]]
    lines = [
        "/* generated by keyboard/tools/gen_zmk_layout.py from the ergogen geometry - do not edit */",
        "",
        "#include <physical_layouts.dtsi>",
        "#include <dt-bindings/zmk/matrix_transform.h>",
        "",
        "/ {",
        "    tsumugi_transform: tsumugi_transform {",
        '        compatible = "zmk,matrix-transform";',
        "        columns = <12>;",
        "        rows = <4>;",
        "        map = <",
    ]
    lines += ["            " + " ".join(r) for r in rows]
    lines += [
        "        >;",
        "    };",
        "",
        "    tsumugi_layout: tsumugi_layout {",
        '        compatible = "zmk,physical-layout";',
        '        display-name = "Tsumugi 44";',
        "        transform = <&tsumugi_transform>;",
        "        kscan = <&kscan0>;",
        "        //                        w    h     x     y       r    rx    ry",
        "        keys",
    ]
    for i, a in enumerate(attrs):
        lines.append(("            = " if i == 0 else "            , ") + a)
    lines += ["            ;", "    };", "};", ""]
    open(out, "w").write("\n".join(lines))
    print(f"wrote {len(attrs)} keys to {out}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
